# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YLB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YLB

	pod 'AFNetworking'	
    
    pod 'Masonry'
    
    pod 'SVProgressHUD'

    pod 'PPNetworkHelper'
    

end
